#!/usr/bin/env python 
# Licensed under a 3-clause BSD style license, see LICENSE.

#-----------------------------------------------------------------------------
# Import statements
#-----------------------------------------------------------------------------
from skhep import *

#-----------------------------------------------------------------------------
# Print the project information - banner and package information
#-----------------------------------------------------------------------------
print( banner )

_proj_info = """Project URLs:
 Homepage %s
 GitHub   %s
 PyPI     %s
""" % ( project_url, project_url_GitHub, project_url_PyPI )

print( _proj_info )
