#!/usr/bin/env python 
# Licensed under a 3-clause BSD style license, see LICENSE.

#-----------------------------------------------------------------------------
# Import statements
#-----------------------------------------------------------------------------
import skhep

#-----------------------------------------------------------------------------
# Print the project information - banner and package information
#-----------------------------------------------------------------------------
_banner = """
   _____      _ _    _ _          _    _ ______ _____
  / ____|    (_) |  (_) |        | |  | |  ____|  __ \ 
 | (___   ___ _| | ___| |_  ____ | |__| | |__  | |__) | 
  \___ \ / __| | |/ / | __| ____ |  __  |  __| |  ___/ 
  ____) | (__| |   <| | |_       | |  | | |____| | 
 |_____/ \___|_|_|\_\_|\__|      |_|  |_|______|_|      {0}

"""
_default = '\x1b[00m'
_green   = '\x1b[32;32m'

print( _green + _banner.format(skhep.__version__) + _default )

_proj_info = """Homepage %s
GitHub   %s
PyPI     %s
""" % ( skhep.project_url, skhep.project_url_GitHub, skhep.project_url_PyPI )

print( _proj_info )
