#!/usr/bin/env python 
# Licensed under a 3-clause BSD style license, see LICENSE.

#-----------------------------------------------------------------------------
# Import statements
#-----------------------------------------------------------------------------
from skhep import *

#-----------------------------------------------------------------------------
# Print the project information - banner and package information
#-----------------------------------------------------------------------------
_default = '\x1b[00m'
_green   = '\x1b[32;32m'

print( _green + banner + _default )

_proj_info = """Homepage %s
GitHub   %s
PyPI     %s
""" % ( project_url, project_url_GitHub, project_url_PyPI )

print( _proj_info )
