#!/usr/bin/env python
# Licensed under a 3-clause BSD style license, see LICENSE.
"""
Test the examples embedded in the documentation of all skhep (sub)packages.
Makes use of the built-in doctest module.

Options
-------
-v : run doctest in verbose mode
"""

#-----------------------------------------------------------------------------
# Import statements
#-----------------------------------------------------------------------------
from optparse import OptionParser
from os       import walk, path
import doctest
import skhep

#-----------------------------------------------------------------------------
# Instantiate a handy parser
#-----------------------------------------------------------------------------
_usage = "%prog [options]"

parser = OptionParser( _usage )

parser.add_option( '-v',
                   '--verbose',
                   action = 'store_true',
                   dest = 'verbose',
                   help = 'run doctest in VERBOSE mode [default: False]'
                   )

( options, args ) = parser.parse_args()

#-----------------------------------------------------------------------------
# Recursively run doctest over all .py files
#-----------------------------------------------------------------------------
matches   = []
skheppath = path.dirname( path.abspath(skhep.__file__) )

for root, dirs, files in walk( skheppath ):
    py_files = [ f for f in files if path.splitext(path.join(root,f))[1] == '.py' ]
    matches.extend( [ path.join(root,f) for f in py_files if py_files !=[] ] )

for m in matches:
    test_result = doctest.testfile(m, module_relative=False, verbose=options.verbose)
    if test_result.attempted > 0 :
       print 'Doctest: %-30s --> %2s tests, %2s OK' %\
	 ( m.split('skhep/')[1], test_result.attempted, (test_result.attempted-test_result.failed) )
